-- stg_company_snapshots.sql
-- ============================================================
-- COMPANY MONTHLY STATUS HISTORY
-- ============================================================
-- One row per (company_id, snapshot_month) — the status of each
-- company at the end of that calendar month.
--
-- DEMO SOURCE: seeds/company_monthly_status.csv
--   Generated by ingestion/generate_seeds.py to simulate the output
--   of snapshots/company_snapshot.sql run on a schedule.
--
-- PRODUCTION SOURCE: snapshots/company_snapshot.sql
--   Replace this ref with the snapshot table once live data is available.
--   The snapshot runs daily/weekly and appends changed rows automatically.
--   Map dbt_valid_from → snapshot_month to align with this model's grain.
-- ============================================================

with source as (
    select * from {{ ref('raw_company_snapshots') }}
)

select
    company_id,
    snapshot_month::date    as snapshot_month,
    company_tier,
    is_active::boolean      as is_active,
    mrr_usd::numeric        as mrr_usd
from source
